---
- name: Install MySQL
  apt: pkg=mysql-server state=present

- name: Creates app_dev user with passowrd app_dev
  mysql_user: name=app_dev password=app_dev priv=*.*:ALL state=present

- name: Copy mysql schema
  copy: src=app_dev_schema.sql dest=/var/www/app.dev/tmp/app_dev_schema.sql

- name: Create app_dev database  
  mysql_db: name=app_dev state=present

- name: Create app_dev database schema 
  mysql_db: name=app_dev state=import target=/var/www/app.dev/tmp/app_dev_schema.sql