---
- hosts: all
  vars:
    apt_key_id: 58118E89F3A912897C070ADBF76221572C52609D
    apt_key_server: hkp://ha.pool.sks-keyservers.net:80

  tasks:
    - name: install required packages
      apt: name={{ item }} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: add apt key from docker
      apt_key: keyserver={{apt_key_server}} id={{apt_key_id}}

    - name: add docker repository
      apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

    - name: update apt 
      apt: update_cache=yes

    - name: update apt and install docker-engine
      apt: name=docker-engine state=latest

    - debug: 
        msg: "OK"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'
