---
- hosts: all
  vars:
    apt_key_id: 58118E89F3A912897C070ADBF76221572C52609D
    apt_key_server: hkp://ha.pool.sks-keyservers.net:80

  tasks:
    - name: install required packages
      apt: name={{ item }} state=installed
      with_items:
        - apt-transport-https
        - ca-certificates

    - name: add apt key from docker
      apt_key: keyserver={{apt_key_server}} id={{apt_key_id}}

    - debug: 
        msg: "{{ansible_lsb}}"

    - debug: 
        msg: "{{ansible_lsb.major_release}}"

    - debug: 
        msg: "{{ansible_os_family}}"

    - debug: 
        msg: "OK"
      when: ansible_os_family == "Ubuntu" and ansible_lsb.release == "14.04"

    # - shell: echo "Ubuntu 16.04"
    #   when: ansible_os_family == "Ubuntu" and ansible_lsb.major_release = "16.04"