---
- hosts: all
  vars:
    proxy_env: 
      http_proxy: http://172.16.0.89:80
      https_proxy: http://172.16.0.89:80

  tasks:
    - name: install required packages
      apt: name={{ item }} state=installed
      with_items:
        - python-pip

    - name: install flask
      pip: name=Flask
